version: "3.9"
services:
  app:
    image: my_prj_app:prod
    # Använder prod i containernamnet för att markera skillnaden på dev.
    container_name: my_app_prod
    build:
      context: ./app
      dockerfile: ../Dockerfile.prod
    links:
      - db
    ports:
      # Använder Flask default port i prod-varianten av imagen.
      - "5000:5000"
    networks:
      my_net_prod:

  db:
    image: mysql
    container_name: my_db_prod
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passw
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      my_net_prod:

# Skapar ett gemensamt lokalt där tjänstena kan kommunicera.
networks:
  my_net_prod:

# docker-compose -f docker-compose-prod.yml up
# docker-compose -f docker-compose-prod.yml stop