FROM python:3.9-alpine
WORKDIR /app
COPY requirements.txt .
COPY app .
RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev
RUN pip install -r requirements.txt
EXPOSE 5000
ENTRYPOINT ["python"]
CMD ["rest.py"]